import type Job from './entities/Job';
import type { Callback, DiscoverDevicesCallback, LogoutReasonCallback, NPRequest, TransactionCallback } from './types';
import type VerifyResult from './Models/VerifyResult';
import type { Terminal } from './Models/Terminal';
import type { TransactionReceiptModel } from './Models/TransactionModel';
import type { ReconciliationListModel } from './Models/ReconciliationListModel';
import type { ReceiptModel } from './Models/ReconciliationModel';
import type { TransactionListModel } from './Models/TransactionListModel';
export declare class NearpayConnect {
    private core;
    private auth;
    private terminal;
    private proxy;
    private emitter;
    constructor();
    startListners(): void;
    onProxyPaired(callback: Callback): void;
    onProxyUnpaired(callback: Callback): void;
    onProxyConnected(callback: Callback): void;
    onProxyDisconnected(callback: Callback): void;
    startDeviceDiscovery(callback: DiscoverDevicesCallback): void;
    onLogout(callback: LogoutReasonCallback): void;
    onPause(callback: Callback): void;
    onResume(callback: Callback): void;
    onDisconnect(callback: Callback): void;
    onReconnectSuggestion(callback: Callback): void;
    onStatusChange(callback: Callback): void;
    onPurchase(callback: TransactionCallback): void;
    onRefund(callback: TransactionCallback): void;
    onReverse(callback: Callback): void;
    onReconciliation(callback: Callback): void;
    onCancelPurchase(callback: Callback): void;
    onCancelRefund(callback: Callback): void;
    onCancelReverse(callback: Callback): void;
    onCancelReconciliation(callback: Callback): void;
    onJobStatusChange(callback: Callback): void;
    onEvent(callback: Callback): void;
    onJobError(callback: Callback): void;
    onTerminalError(callback: Callback): void;
    build(port: number, environment: string, networkConfiguration: string, loadingUi: boolean, deviceName: string): Promise<any>;
    showConnection(): Promise<any>;
    startConnection(): Promise<any>;
    stopConnection(): Promise<any>;
    stopDeviceDiscovery(): Promise<boolean>;
    connect(timeout: number, ip: string, port: string): Promise<boolean>;
    disconnect(): Promise<boolean>;
    ping(timeout: number): Promise<boolean>;
    login(method: string, value: string, timeout: number): Promise<any>;
    verify(otp: string, timeout: number): Promise<VerifyResult>;
    getTerminalList(timeout: number): Promise<Terminal[]>;
    logout(timeout: number): Promise<boolean>;
    connectTerminal(terminalID: string, timeout: number): Promise<string>;
    disconnectFromCurrentTerminal(timeout: number): Promise<boolean>;
    getInfo(timeout: number): Promise<any>;
    purchase(purchaseData: NPRequest): Promise<any>;
    refund(refundData: NPRequest): Promise<any>;
    reverse(reverseData: NPRequest): Promise<any>;
    reconcile(reconcileData: NPRequest): Promise<any>;
    start(job: Job): Promise<any>;
    cancel(job: Job): Promise<any>;
    getTransaction(transactionRequest: NPRequest): Promise<TransactionReceiptModel>;
    getReconciliation(reconciliationRequest: NPRequest): Promise<ReceiptModel>;
    getTransactionList(transactionListRequest: NPRequest): Promise<TransactionListModel>;
    getReconciliationList(reconciliationListRequest: NPRequest): Promise<ReconciliationListModel>;
    disconnectTerminal(timeout: number): Promise<any>;
}
//# sourceMappingURL=index.d.ts.map